[dev]
  command = "npx react-native start --reset-cache" # Replace with your start command
  port = 8888
  targetPort = 8081 # The port your React Native app runs on
  autoLaunch = false # Prevent Netlify Dev from opening a browser window

[functions]
  directory = "netlify/functions"